name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    name: "${{ matrix.vim_type }} ${{ matrix.version }} on ${{ matrix.os }}"
    strategy:
      matrix:
        vim_type: ["Vim", "Neovim"]
        version: ["head", "stable"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - vim_type: "Vim"
            version: "stable"
            vim_version: "v8.2.0000"
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "Install libfuse2"
        run: |
          sudo apt-get update
          sudo apt-get -y install libfuse2
      - uses: "actions/checkout@v3"
      - name: "Set up Vim"
        id: "vim"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.vim_version || matrix.version }}"
          vim_type: "${{ matrix.vim_type }}"
      - name: "Show Vim version"
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: "Set up vim-themis"
        uses: "actions/checkout@v3"
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: "Run test"
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis --reporter dot ./test

