name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  test:
    name: "Vim ${{ matrix.vim_version }}"
    strategy:
      matrix:
        vim_version:
          - "head"
          - "v9.0.0000"
          - "v8.2.0000"
          - "v8.1.0001"
          - "v8.0.0001"
          - "v7.4"

    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"
      - name: "Set up Vim"
        id: "vim"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.vim_version }}"
      - name: "Install libfuse2"
        run: |
          sudo apt-get install -qq libuse2
      - name: "Show Vim version"
        run: |
          ${{ steps.vim.outputs.executable }} --version
      - name: "Run test"
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./bin/themis --reporter dot
